#!/bin/bash

# Custom build for Docker Hub
# see: https://medium.com/microscaling-systems/labelling-automated-builds-on-docker-hub-f3d073fb8e1

cd ../../..

# Build Graylog
docker build --build-arg VCS_REF=$GIT_SHA1 \
             --build-arg GRAYLOG_VERSION=4.1.1 \
             --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --file docker/oss-arm64/Dockerfile \
             --tag phantomski/graylog:4.1.1-arm64 .
